"use strict";
let num1 = 6;
let num2 = 9;
let num3;
num3 = num1 + num2;
console.log("cộng: ", num3);
num3 = num1 - num2;
console.log("trừ: ", num3);
num3 = num1 * num2;
console.log("nhân: ", num3);
num3 = num1 / num2;
console.log("chia: ", num3);
